### ISSUE TITLE
Original Battery Max Capacity

### ISSUE THREAD

**Issue by slvrscoobie** [codler/Battery-Time-Remaining#100]
I'd love to see a simple addition of the max original capacity of the battery, and maybe even a 'health' (current max/original max) added. I know Battery Health offers this. Would make this project complete to me!!

**Comment by codler** [comment]
Why would you want to know original max?

**Comment by slvrscoobie** [comment]
This would give you the ability to know how your battery is aging. If the current maximum charge is only 90% of the original, you'll know that it's beginning to lose its capacity
