### ISSUE TITLE
Not getting notifications when battery is discharging on El Capitan

### ISSUE THREAD

**Issue by vincentroy22** [codler/Battery-Time-Remaining#101]
I'm getting notifications only when plug-in (charging), which is not really helpful since I want to be warned when the battery is discharging.

I'm running El Capitan on a 2013 MacBook Pro Retina. I bought Battery Time Remaining V2 today. In the System's notification settings, I have the alert style set to Alerts to make sure notifications stays on screen until I close them.

Is this a know issue?

**Comment by sciuscia** [comment]
So do you confirm that the application doesn't work as promise?

**Comment by codler** [comment]
@vincentroy22 do the issue still happen?
