### ISSUE TITLE
Compatibility with macOS Sierra (10.12 Beta)

### ISSUE THREAD

**Issue by notDavid** [codler/Battery-Time-Remaining#105]
Hi,

It seems Battery Time Remaining 2 stopped working in macOS Sierra (10.12 Beta).
I can see the app is running in Activity Monitor but i don't see anything happening in the Menu Bar.

I'm running the latest version downloaded from http://yap.nu/battery-time-remaining/download/Battery%20Time%20Remaining%202-3.0.zip

**Comment by JustHyperX** [comment]
Got this issue too the edition picked up here and the App Store App

**Comment by slvrscoobie** [comment]
Same here - its 'running' but nothing shows in menu bar. Hope we can fix it :D

**Comment by hanselsin** [comment]
and it is still not working on the latest GM build 16A323 dated 15-Sept-2016. Please help!

**Comment by EugeneFeingold** [comment]
+1 doesn't work on 10.12 (16A323)

**Comment by nbppp2** [comment]
I have taken a look at the code, and done a little debugging. It looks like the code points to the Apple icons. It looks like the location of those icons has moved for 10.12. The previous location was `/System/Library/CoreServices/Menu Extras/Battery.menu/Contents/Resources/` see AppDelegate.m starting at line 619 to see the names of the files previously.

**Comment by nbppp2** [comment]
It looks like these files have moved to `/System/Library/PrivateFrameworks/BatteryUIKit.framework/Versions/A/Resources/` in macOS Sierra (10.12). I will make some changes to the code to support this and make a PR shortly. If anyone else is more versed in Objective-C and Mac development, feel free to beat me to the PR.

**Comment by nbppp2** [comment]
#106 Is my PR to fix this issue.

**Comment by nbppp2** [comment]
I have published a build of the app [here](https://github.com/nbppp2/Battery-Time-Remaining/releases/tag/v3.0.2)

**Comment by EugeneFeingold** [comment]
Works! Thanks!

**Comment by slvrscoobie** [comment]
ITS BACK! :D YAY!! THANK YOU!

**Comment by es0phagus** [comment]
Thanks so much

**Comment by hanselsin** [comment]
Thank you! It works like a charm!

**Comment by alexbotev** [comment]
No, it does not work. I had version 1.x, bought 2.x (now 3.1) because it was mentioned that it should work but it doesn't :( can you fix it please

**Comment by purplespud** [comment]
Thanks so very  much nbppp2!

**Comment by JustHyperX** [comment]
Works! Thanks c",)

**Comment by codler** [comment]
An update are on its way

**Comment by Turbo87** [comment]
@codler could you update http://yap.nu/battery-time-remaining/ with the new releases too?

**Comment by codler** [comment]
Having some trouble setting up my developer id on new computer..
