### ISSUE TITLE
Any plan to get v4.0 to download from http://yap.nu/battery-time-remaining/

### ISSUE THREAD

**Issue by pplucky** [codler/Battery-Time-Remaining#109]
Although v4.0 is available in GitHub, I cannot seem to find it to download in http://yap.nu/battery-time-remaining/.

Is there any plan to when it will be available to download from there?

Thanks in advance.

**Comment by mikasgist** [comment]
I agree with pplucky!  http://yap.nu/battery-time-remaining/ does not have the latest version 4.0.  I'm just a user, and don't know how to code the files available in GitHub.

Please, is there any plan and date when version 4 will be available to download from http://yap.nu/battery-time-remaining/ ?

Thank you so much!

**Comment by kishorebabu8** [comment]
*bump*
