### ISSUE TITLE
not working under 10.13.4 (17E202)

### ISSUE THREAD

**Issue by okocsis** [codler/Battery-Time-Remaining#112]
this is what I get when I try to start it up from cmd:
```
$ /Applications/Battery\ Time\ Remaining\ 2.app/Contents/MacOS/Battery\ Time\ Remaining\ 2
2018-05-28 00:31:30.897 Battery Time Remaining 2[3178:60921] Cannot lock focus on image <NSImage 0x7f8b17428da0 Size={0, 0} Reps=(
)>, because it is size zero.
```

**Comment by SannePetersNL** [comment]
Same problem here  10.13.5

**Comment by codler** [comment]
What macbook are you using? It works for me in MBA 13" mid 2011 and MBP 15" retina mid 2015

**Comment by SannePetersNL** [comment]
@codler MacBook Air 13-inch, 2017

**Comment by maatthc** [comment]
Hi there,
I've cloned and built the project and it is working well. I'm using Mojave 10.14.6.
The binary is available at https://www.maat.com.br/wp-content/uploads/2020/04/Battery-Time-Remaining-2.zip
