### ISSUE TITLE
Not working under 10.14 MacOS Mojave

### ISSUE THREAD

**Issue by olka14** [codler/Battery-Time-Remaining#113]
Error message:
Battery Time Remaining 2 (Launchservices)
27366555: RECEIVED OUT-OF-SEQUENCE NOTIFICATION: 1024 vs 1229, 512, <private>

**Comment by stevechen** [comment]
I bought a copy from the App Store. I could run it, but the notification does nothing…

**Comment by maatthc** [comment]
Hi there,
I've cloned and built the project and it is working well. I'm using Mojave 10.14.6.
The binary is available at https://www.maat.com.br/wp-content/uploads/2020/04/Battery-Time-Remaining-2.zip
