### ISSUE TITLE
macOS High Sierra 10.13.6

### ISSUE THREAD

**Issue by krsiakdaniel** [codler/Battery-Time-Remaining#114]
- installed
- icon does not show
- wanted to delete it
- tells me it is open

Cannot use and cannot delete. 
What now?

![screenshot](https://user-images.githubusercontent.com/564906/46824202-6e0b0200-cd90-11e8-9db5-bc62415fa028.png)

**Comment by codler** [comment]
You are using a very old version of app.
Kill it through activity monitor then you can move.
