### ISSUE TITLE
Make notifications user-dismissable.

### ISSUE THREAD

**Issue by PReinie** [codler/Battery-Time-Remaining#98]
If you are away from your computer or distracted when a notification point is reached you miss it and the next thing you know you get shut down. (It happened to me a day ago.)

I'd like to be able to set each notification with an option that requires the user to dismiss the notification. For the percentages above 20 or 30% I would personally have the notification go away automatically, but at say 30% I would like to have it stay up until I dismiss it, and put up another notification for each marked notification point, or if that's too much coding at least replace the current undismissed notification. (Decisions would have to be made if 10% wasn't marked user-must-dismiss but 20% was marked user-must-dismiss. I'd replace 20% with 10% and leave it up for dismissal.)
At a percentage around 5% - a few minutes before shut down it should start audio alerting you frequently and audio alert frequently earlier if you've been inactive.
Maybe even text your mobile if you're in another room if you set that up. (You can email a text to a phone, like mailto:1234567890@vtext.com "Your <machineName> laptop battery is at 10%. Please plug it in!".)
I'm considering forking the code, but I know little OO coding (some Ruby). I've done multiple assembly languages, Fortran, C and scripting so I'd likely be unhelpful.
Obviously this is an enhancement.

**Comment by codler** [comment]
In the OS, System Settings > Notifications you can setup to manually dismiss nofitications.
